# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CScrapy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(468, 174, 101, 41))
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_start.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"font: 9pt \"微软雅黑\";")
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_T = QtWidgets.QLabel(self.centralwidget)
        self.label_T.setGeometry(QtCore.QRect(150, 100, 131, 51))
        self.label_T.setMinimumSize(QtCore.QSize(0, 0))
        self.label_T.setMaximumSize(QtCore.QSize(16777215, 167777))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_T.setFont(font)
        self.label_T.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_T.setAutoFillBackground(False)
        self.label_T.setStyleSheet("background-color: rgb(20, 185, 200);\n"
"color: rgb(255, 255, 255);")
        self.label_T.setText("")
        self.label_T.setObjectName("label_T")
        self.radioButton_Tap = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Tap.setGeometry(QtCore.QRect(175, 110, 81, 32))
        self.radioButton_Tap.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.radioButton_Tap.setFont(font)
        self.radioButton_Tap.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.radioButton_Tap.setChecked(True)
        self.radioButton_Tap.setObjectName("radioButton_Tap")
        self.label_B = QtWidgets.QLabel(self.centralwidget)
        self.label_B.setGeometry(QtCore.QRect(330, 100, 131, 51))
        self.label_B.setMinimumSize(QtCore.QSize(0, 0))
        self.label_B.setMaximumSize(QtCore.QSize(16777215, 167777))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_B.setFont(font)
        self.label_B.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_B.setAutoFillBackground(False)
        self.label_B.setStyleSheet("background-color: rgb(251, 114, 153);\n"
"color: rgb(255, 255, 255);")
        self.label_B.setText("")
        self.label_B.setObjectName("label_B")
        self.radioButton_Bili = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Bili.setGeometry(QtCore.QRect(360, 110, 81, 32))
        self.radioButton_Bili.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.radioButton_Bili.setFont(font)
        self.radioButton_Bili.setAutoFillBackground(False)
        self.radioButton_Bili.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.radioButton_Bili.setChecked(False)
        self.radioButton_Bili.setObjectName("radioButton_Bili")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 250, 501, 181))
        self.textBrowser.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 230, 54, 12))
        self.label.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 180, 71, 31))
        self.label_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 180, 61, 31))
        self.label_3.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_appid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_appid.setGeometry(QtCore.QRect(143, 180, 131, 31))
        self.lineEdit_appid.setObjectName("lineEdit_appid")
        self.lineEdit_page_total = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_page_total.setGeometry(QtCore.QRect(370, 180, 71, 31))
        self.lineEdit_page_total.setObjectName("lineEdit_page_total")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 20, 481, 51))
        self.label_4.setStyleSheet("font: 75 25pt \"微软雅黑\";\n"
"color: rgb(85, 170, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_T.raise_()
        self.label_B.raise_()
        self.pushButton_start.raise_()
        self.radioButton_Tap.raise_()
        self.radioButton_Bili.raise_()
        self.textBrowser.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_appid.raise_()
        self.lineEdit_page_total.raise_()
        self.label_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CScrapy"))
        self.pushButton_start.setText(_translate("MainWindow", "开始获取"))
        self.radioButton_Tap.setText(_translate("MainWindow", "TapTap"))
        self.radioButton_Bili.setText(_translate("MainWindow", "BILIBILI"))
        self.label.setText(_translate("MainWindow", "获取进度："))
        self.label_2.setText(_translate("MainWindow", "游戏AppID："))
        self.label_3.setText(_translate("MainWindow", "爬取页数："))
        self.label_4.setText(_translate("MainWindow", "一键快速获取游戏评论内容"))
